apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable
  namespace: flux-system
spec:
  url: https://charts.helm.sh/stable
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: memcached
      version: "3.2.5"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
      interval: 1m
  # values:
  
